# Change 'comments' to true for Disqus comments
disqus:
  comments: false

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: '.', url: 'about'}
- {name: 'Publications', path: '.', url: 'publications'}
- {name: 'Photography', path: '.', url: 'photography'}
- {name: 'Blog', path: '.', url: 'blog'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/misev'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/dimitarmisev/'}
- {icon: 'instagram', link: 'http://www.instagram.com/dimitarmisev/'}
- {icon: 'envelope', link: 'mailto:contact@dimitarmisev.com'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share.'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Published on'
